#!/bin/bash

set -e

#
# Launches tools from docker haskel platform image.
#

# docker-machine systems will link the docker daemon to the mst container via tcp
if [ $DOCKER_HOST ] ;
  then HOST_DOCKER_LINKAGE="-e DOCKER_HOST=$DOCKER_HOST $HOST_DOCKER_LINKAGE"
fi;

if [ $DOCKER_TLS_VERIFY ] ;
  then HOST_DOCKER_LINKAGE="-e DOCKER_TLS_VERIFY=$DOCKER_TLS_VERIFY $HOST_DOCKER_LINKAGE"
fi;

if [ $DOCKER_CERT_PATH ] ;
  then HOST_DOCKER_LINKAGE="-e DOCKER_CERT_PATH=$DOCKER_CERT_PATH $HOST_DOCKER_LINKAGE"
fi;

[ -d "$HOME/.alpine" ] || mkdir "$HOME/.alpine"
[ -d "$HOME/.alpine/local" ] || mkdir "$HOME/.alpine/local"
[ -d "$HOME/.alpine/stack" ] || mkdir "$HOME/.alpine/stack"

CWD="$(pwd -P)"

exec docker run \
  -it \
  --rm \
  -e PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  -e HOME="$HOME" \
  -e STACK_OPTS="--system-ghc --skip-ghc-check --ghc-options '-optl-static'" \
  $HOST_DOCKER_LINKAGE \
  --user "$(id -u):$(id -g)" \
  --mount "type=tmpfs,target=$HOME" \
  --mount "type=bind,source=$HOME/.alpine/local,target=$HOME/.local" \
  --mount "type=bind,source=$HOME/.alpine/stack,target=$HOME/.stack" \
  --mount "type=bind,source=$CWD,target=$CWD" \
  --mount "type=bind,source=$HOME/.gnupg,target=$HOME/.gnupg" \
  -w "$CWD" \
  andreyk0/docker-haskell-platform-alpine:latest "$@"
