#!/bin/bash

# Alpine-based dockerized static GHC/stack build

#
# Tested with stackage lts-8.4
#

set -e
set -x

# STACK_OPTS are defined in the container
docker-haskell-platform-alpine stack install '$STACK_OPTS'

# compress the last binary installed
E=`ls -rt ~/.alpine/local/bin | tail -1`

docker-haskell-platform-alpine upx --best $HOME/.local/bin/$E
